# Dependencies
markdown:         kramdown
highlighter:      rouge
remote_theme: nandomoreirame/simplest

# Permalinks
permalink:        pretty

# Setup
title:            Ryan Stewart
tagline:          'FPMRS Fellow'
description:      'Female Pelvic Surgeon in Louisville, KY.'
url:              http://ryanstewart.com
baseurl:          /

author:
  name:           'Ryan Stewart'
  url:            https://twitter.com/stuboo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/stuboo

gems:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - pygments.rb
  
plugins:
  - jekyll-include-cache